// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.0
// source: resource.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExistSiteLineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceId   uint64 `protobuf:"varint,1,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	NextId       uint64 `protobuf:"varint,2,opt,name=nextId,proto3" json:"nextId,omitempty"`
	ResourceType uint64 `protobuf:"varint,3,opt,name=resourceType,proto3" json:"resourceType,omitempty"`
	NextType     uint64 `protobuf:"varint,4,opt,name=nextType,proto3" json:"nextType,omitempty"`
}

func (x *ExistSiteLineRequest) Reset() {
	*x = ExistSiteLineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_exist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistSiteLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistSiteLineRequest) ProtoMessage() {}

func (x *ExistSiteLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resource_exist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistSiteLineRequest.ProtoReflect.Descriptor instead.
func (*ExistSiteLineRequest) Descriptor() ([]byte, []int) {
	return file_resource_exist_proto_rawDescGZIP(), []int{0}
}

func (x *ExistSiteLineRequest) GetResourceId() uint64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *ExistSiteLineRequest) GetNextId() uint64 {
	if x != nil {
		return x.NextId
	}
	return 0
}

func (x *ExistSiteLineRequest) GetResourceType() uint64 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *ExistSiteLineRequest) GetNextType() uint64 {
	if x != nil {
		return x.NextType
	}
	return 0
}

type ExistSiteLineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsExist bool `protobuf:"varint,1,opt,name=isExist,proto3" json:"isExist,omitempty"`
}

func (x *ExistSiteLineResponse) Reset() {
	*x = ExistSiteLineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resource_exist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExistSiteLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistSiteLineResponse) ProtoMessage() {}

func (x *ExistSiteLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resource_exist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistSiteLineResponse.ProtoReflect.Descriptor instead.
func (*ExistSiteLineResponse) Descriptor() ([]byte, []int) {
	return file_resource_exist_proto_rawDescGZIP(), []int{1}
}

func (x *ExistSiteLineResponse) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

var File_resource_exist_proto protoreflect.FileDescriptor

var file_resource_exist_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x14, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x53, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x6e, 0x65, 0x78, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x65, 0x78, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6e,
	0x65, 0x78, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x31, 0x0a, 0x15, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x53, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x32, 0x51, 0x0a, 0x0b, 0x53, 0x69,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x69, 0x73, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x53, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x53, 0x69, 0x74, 0x65, 0x4c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_resource_exist_proto_rawDescOnce sync.Once
	file_resource_exist_proto_rawDescData = file_resource_exist_proto_rawDesc
)

func file_resource_exist_proto_rawDescGZIP() []byte {
	file_resource_exist_proto_rawDescOnce.Do(func() {
		file_resource_exist_proto_rawDescData = protoimpl.X.CompressGZIP(file_resource_exist_proto_rawDescData)
	})
	return file_resource_exist_proto_rawDescData
}

var file_resource_exist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_resource_exist_proto_goTypes = []interface{}{
	(*ExistSiteLineRequest)(nil),  // 0: ExistSiteLineRequest
	(*ExistSiteLineResponse)(nil), // 1: ExistSiteLineResponse
}
var file_resource_exist_proto_depIdxs = []int32{
	0, // 0: SiteService.isExistResource:input_type -> ExistSiteLineRequest
	1, // 1: SiteService.isExistResource:output_type -> ExistSiteLineResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resource_exist_proto_init() }
func file_resource_exist_proto_init() {
	if File_resource_exist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resource_exist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistSiteLineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resource_exist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExistSiteLineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resource_exist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resource_exist_proto_goTypes,
		DependencyIndexes: file_resource_exist_proto_depIdxs,
		MessageInfos:      file_resource_exist_proto_msgTypes,
	}.Build()
	File_resource_exist_proto = out.File
	file_resource_exist_proto_rawDesc = nil
	file_resource_exist_proto_goTypes = nil
	file_resource_exist_proto_depIdxs = nil
}
